
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package edu.unitec.matrox;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FUNCTION = 15;
  public static final int CHAR = 3;
  public static final int CASE = 12;
  public static final int DOUBLE = 5;
  public static final int INTEGER = 2;
  public static final int GREATER = 30;
  public static final int LESS = 31;
  public static final int FOR = 10;
  public static final int WRITE = 17;
  public static final int AND = 36;
  public static final int NOT = 34;
  public static final int RPAR = 25;
  public static final int OR = 35;
  public static final int COMMA = 19;
  public static final int DIV = 23;
  public static final int ASSIGN = 37;
  public static final int MIN = 21;
  public static final int LESSEQ = 29;
  public static final int IF = 7;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int RETURN = 16;
  public static final int error = 1;
  public static final int MUL = 22;
  public static final int ADD = 20;
  public static final int DOUBLENUMBER = 40;
  public static final int NEQ = 32;
  public static final int BREAK = 13;
  public static final int SWITCH = 11;
  public static final int LBRACK = 26;
  public static final int EQU = 33;
  public static final int ELSE = 8;
  public static final int READ = 18;
  public static final int RBRACK = 27;
  public static final int WHILE = 9;
  public static final int END = 14;
  public static final int LPAR = 24;
  public static final int GREATEREQ = 28;
  public static final int STRING = 6;
  public static final int INTNUMBER = 39;
  public static final int IDENTIFIER = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "CHAR",
  "BOOLEAN",
  "DOUBLE",
  "STRING",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "SWITCH",
  "CASE",
  "BREAK",
  "END",
  "FUNCTION",
  "RETURN",
  "WRITE",
  "READ",
  "COMMA",
  "ADD",
  "MIN",
  "MUL",
  "DIV",
  "LPAR",
  "RPAR",
  "LBRACK",
  "RBRACK",
  "GREATEREQ",
  "LESSEQ",
  "GREATER",
  "LESS",
  "NEQ",
  "EQU",
  "NOT",
  "OR",
  "AND",
  "ASSIGN",
  "IDENTIFIER",
  "INTNUMBER",
  "DOUBLENUMBER"
  };
}

