
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package edu.unitec.matrox;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHARCONTENT = 46;
  public static final int FUNCTION = 18;
  public static final int CHAR = 3;
  public static final int CASE = 14;
  public static final int DOUBLE = 5;
  public static final int INTEGER = 2;
  public static final int GREATER = 35;
  public static final int LESS = 36;
  public static final int FOR = 12;
  public static final int WRITE = 21;
  public static final int AND = 41;
  public static final int NOT = 39;
  public static final int RPAR = 30;
  public static final int OR = 40;
  public static final int COMMA = 23;
  public static final int DIV = 28;
  public static final int ASSIGN = 42;
  public static final int MIN = 26;
  public static final int LESSEQ = 34;
  public static final int IF = 9;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int RETURN = 19;
  public static final int TRUE = 7;
  public static final int error = 1;
  public static final int MUL = 27;
  public static final int ADD = 25;
  public static final int DOUBLENUMBER = 45;
  public static final int NEQ = 37;
  public static final int BREAK = 15;
  public static final int VOID = 20;
  public static final int SWITCH = 13;
  public static final int LBRACK = 31;
  public static final int EQU = 38;
  public static final int COLON = 24;
  public static final int ELSE = 10;
  public static final int READ = 22;
  public static final int RBRACK = 32;
  public static final int WHILE = 11;
  public static final int DEFAULT = 16;
  public static final int END = 17;
  public static final int LPAR = 29;
  public static final int GREATEREQ = 33;
  public static final int STRING = 6;
  public static final int FALSE = 8;
  public static final int STRINGCONTENT = 47;
  public static final int INTNUMBER = 44;
  public static final int IDENTIFIER = 43;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "CHAR",
  "BOOLEAN",
  "DOUBLE",
  "STRING",
  "TRUE",
  "FALSE",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "SWITCH",
  "CASE",
  "BREAK",
  "DEFAULT",
  "END",
  "FUNCTION",
  "RETURN",
  "VOID",
  "WRITE",
  "READ",
  "COMMA",
  "COLON",
  "ADD",
  "MIN",
  "MUL",
  "DIV",
  "LPAR",
  "RPAR",
  "LBRACK",
  "RBRACK",
  "GREATEREQ",
  "LESSEQ",
  "GREATER",
  "LESS",
  "NEQ",
  "EQU",
  "NOT",
  "OR",
  "AND",
  "ASSIGN",
  "IDENTIFIER",
  "INTNUMBER",
  "DOUBLENUMBER",
  "CHARCONTENT",
  "STRINGCONTENT"
  };
}

